version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: production
    container_name: higo-app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://higouser:higopassword@mongodb:27017/higoapp
      - REDIS_URL=redis://:higoredispassword@redis:6379
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-30d}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - higo-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    build:
      context: docker/mongodb
      dockerfile: Dockerfile
    container_name: higo-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=higoapp
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-logs:/var/log/mongodb
    networks:
      - higo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    build:
      context: docker/redis
      dockerfile: Dockerfile
    container_name: higo-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - higo-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "higoredispassword", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb-data:
    driver: local
  mongodb-logs:
    driver: local
  redis-data:
    driver: local

networks:
  higo-network:
    driver: bridge